-- CreateTable
CREATE TABLE "Synth" (
    "id" SERIAL NOT NULL,
    "uid" INTEGER NOT NULL,
    "sigma" DOUBLE PRECISION NOT NULL,
    "dt" DOUBLE PRECISION NOT NULL,
    "flag" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Synth_pkey" PRIMARY KEY ("id")
);
